Bump netty tcnative version (#2686)
Bump netty tcnative boringssl static version to 2.0.55.Final

I've been seeing exceptions like this
java.lang.NoSuchFieldError: SSL_MAX_ENCRYPTED_LENGTH at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$DefaultOpenSslSession.getPacketBufferSize(ReferenceCountedOpenSslEngine.java:2652) ~[io.netty.netty-handler-4.1.94.Final.jar:4.1.94.Final]

This field SSL_MAX_ENCRYPTED_LENGTH doesn't exist in the current version of tcnative. I looked up on the github, it was introduced at next version. So bump this version to fix this error.